# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15-hOhv6HvSdZIYOnrTD0U6ibbFhmST7J
"""

import numpy as np

import pandas as pd

resources = [120, 200, 350, 400]

capacity = int(input())

vector = np.array(resources)

coefs = vector / pd.Series(resources).sum()

get_resources = coefs * capacity

result = [int(x) for x in np.floor(get_resources)]

result
